apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-staging
  namespace: argocd
spec:
  project: hello-world-project
  source:
    repoURL: 'https://github.com/spanozzo/HelloKubeOps.git'
    targetRevision: staging
    path: k8s/manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: hello-world-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true